### ISSUE TITLE
logging.log logs all character to \u0000

### ISSUE THREAD

**Issue by ailisp** [nearprotocol/near-runtime-ts#67]
near-runtime-ts version: staging at 4babdd330cd8529fb16a4f4d5af7834a5307b1c5
near-core version: staging at 83453d29826f21f25bdf6904cf218a49dca6e7ce
System: Linux bo-ubuntu 5.0.0-25-generic #26-Ubuntu SMP Thu Aug 1 12:04:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Step to reproduce:
1. in near-runtime-ts/tests. run `npm run build && cp out/main.wasm /tmp`
2. Copy most recent config.json and context.json to /tmp. Download from here:
https://www.dropbox.com/s/c9mpa3fcfwg9f3r/config.json?dl=0
https://www.dropbox.com/s/1v7ov4ghwmsgf4q/context.json?dl=0
3. in nearcore run `cargo run -p near init`
4. in nearcore, run `cargo run --package near-vm-runner-standalone --bin near-vm-runner-standalone -- --context-file=/tmp/context.json --config-file=/tmp/config.json --method-name=base58Test --wasm-file=/tmp/main.wasm --input='{}'`

Error behavior: test passed, but many `\u0000 in `logs`:
```
{"balance":0,"storage_usage":0,"return_data":"None","burnt_gas":58716,"used_gas":58716,"logs":["LOG: \u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000st","LOG: \u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000ncoded value 1TMu"]}
```

Expected behavior: logging correctly.

**Comment by nearmax** [comment]
That's an issue on AssemblyScript side. From debugging I can see that it passes the following bytes to the runtime:
```
[0] = {unsigned char} '\0'
[1] = {unsigned char} '\0'
[2] = {unsigned char} '\0'
[3] = {unsigned char} '\0'
[4] = {unsigned char} '\0'
[5] = {unsigned char} '\0'
[6] = {unsigned char} '\0'
[7] = {unsigned char} '\0'
[8] = {unsigned char} 's'
[9] = {unsigned char} 't'
```

**Comment by bowenwang1996** [comment]
What is the string that you tried to log?

**Comment by nearmax** [comment]
See the contract code. Search `base58Test` in near-runtime-ts

**Comment by ailisp** [comment]
@bowenwang1996 seems any string to log will cause this issue. Try adding `logging.log("some str")` to tests/main.ts and retry 1-4, for example.

**Comment by ailisp** [comment]
Observed this is fixed as of now. Closed
