### ISSUE TITLE
Tests pass even when they panic

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/near-runtime-ts#98]
To reproduce, run tests with the recent version of nearcore and observe:
```
Running promiseTests
[PASS] {"balance":0,"storage_usage":0,"return_data":"None","burnt_gas":2309,"used_gas":2309,"logs":["promiseTests"]}
FunctionCallError(HostError(ProhibitedInView("promise_results_count")))
```

To make it even more obvious, insert the following line in `mathTests`:
```
export function mathTests(): void {
  assert(false, "BAD");
  logging.log("mathTests");
...
```
Then run tests (`yarn build; ./test.sh`) and observe:
```
Running mathTests
[PASS] {"balance":0,"storage_usage":0,"return_data":"None","burnt_gas":863,"used_gas":863,"logs":["ABORT: BAD, filename: \"assembly/main.ts\" line: 454 col: 2"]}
FunctionCallError(HostError(GuestPanic("BAD, filename: \"assembly/main.ts\" line: 454 col: 2")))

14 Total, 13 Passed, 0 Failed, 1 Ignored.
```

**Comment by bowenwang1996** [comment]
maybe related to https://github.com/nearprotocol/nearcore/pull/1887 @mikhailOK

**Comment by nearmax** [comment]
> maybe related to [nearprotocol/nearcore#1887](https://github.com/nearprotocol/nearcore/pull/1887) @mikhailOK

Not related at all. near-runtime-ts uses `near-vm-runner-standalone` which has nothing do to with tokio or actix.
